services:
  - type: web
    name: cryptoshield-api
    runtime: python
    buildCommand: pip install -r cryptoshield_requirements.txt
    startCommand: uvicorn cryptoshield_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
